name: Nubola
favicon: null
layout_spectrum: 0.50875
typography_spectrum: 0.49634
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.14170491229742765
  lightness: 0.20872634137049317
  saturation: 0.0709908977150917
  rhythmicContrast: 0.1467635363806039
purpose: []
